### ISSUE TITLE
ksttobdf large SWIDTH

### ISSUE THREAD

**Issue by larsbrinkhoff** [atsampson/its-tests#6]
Apparently the SWIDTH value is too large:  
https://github.com/Tblue/mkttf/issues/9

The conversion code has a comment `# XXX?` so maybe there's something that needs clarification?  
https://github.com/atsampson/its-tests/blob/fea4291c2c1903aca5b7c454cacd44c5fd5a8bf9/tools/ksttobdf#L126

**Comment by Tblue** [comment]
I think `SWIDTH` is being wrongly calculated here.

The [BDF Spec, p. 9](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5005.BDF_Spec.pdf#page=9) has to say the following regarding `SWIDTH`:

> To convert the scalable width to the width in device pixels, multiply `SWIDTH` times *p*/1000 times *r*/72, where *r* is the device resolution in pixels per inch. The result is a real number giving the ideal width in device pixels. The actual device width must be an integral number of device pixels and is given by the `DWIDTH` entry.

So we could approximate `SWIDTH` $s$ from `DWIDTH` $d$: 
   
$$
\begin{align}
d & = s \times \frac{p}{1000} \times \frac{r}{72} & \iff \\
s & = \frac{d}{\frac{p}{1000} \times \frac{r}{72}} &
\end{align}
$$

For example, for font [40vshd.bdf](https://github.com/larsbrinkhoff/xgp-fonts/blob/master/bdf/40vshd.bdf) by @larsbrinkhoff, we can calculate the `SWIDTH` for glyph `A` (aka `char65`) as follows (with $d = 29 \ \text{px}$, $p = 14 \ \text{pt}$, $r = 200 \ \text{PPI}$):

$$
s = \left\lceil \frac{29}{\frac{14}{1000} \times \frac{200}{72}} \right\rceil = 746 \ \text{px}
$$

An `SWIDTH` of `746` _does_ look a lot more sensible than the current value of `2059`:

![image](https://user-images.githubusercontent.com/842305/232151239-5a7c329f-12f3-4fef-bb35-f816428a825c.png)

**Comment by atsampson** [comment]
I've implemented @Tblue's suggested approach above - does it work better in general now? Is the SIZE entry correct?

**Comment by larsbrinkhoff** [comment]
I re-ran the ksttobdf script and the new SWIDTH values seem in line with @Tblue's suggestion: https://github.com/larsbrinkhoff/xgp-fonts
